# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OBS.Ninja - Guide
description: > # this means to ignore newlines until "url:"
  This is Phantom, a simple design built around a grid of large, colorful, semi-interactive
  image tiles (of which you can have as many or as few as you like). Makes use of some
  SVG and animation techniques I've been experimenting with on that other project of mine
  you may have heard about (https://carrd.co), and includes a handy generic page for whatever.
url: "http://guides.obs.ninja" # the base hostname & protocol for your site

# Contact settings
email: steve@seguin.email
github_username:  steveseguin

# Build settings
markdowm: kramdown

kramdown:
  input:      GFM
  auto_ids:   false

sass:
  style: compact

exclude: ["README.md", "LICENSE.md", "screenshot.png"]